apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    application.giantswarm.io/team: {{ .Values.team }}
    {{- include "irsa-servicemonitors.labels" . | nindent 4 }}
  name: prometheus-blackbox-exporter-http-irsawebhook
  namespace: kube-system
spec:
  endpoints:
  - interval: 30s
    metricRelabelings:
    - action: replace
      sourceLabels:
      - instance
      targetLabel: instance
    - action: replace
      replacement: http-irsawebhook
      sourceLabels:
      - target
      targetLabel: target
    params:
      hostname:
      - {{ "aws-pod-identity-webhook.kube-system.svc.CLUSTERDOMAIN" | replace "CLUSTERDOMAIN" .Values.cluster.kubernetes.clusterDomain }}
      module:
      - http_irsa_webhook
      target:
      - {{ "https://aws-pod-identity-webhook.kube-system.svc.CLUSTERDOMAIN/mutate" | replace "CLUSTERDOMAIN" .Values.cluster.kubernetes.clusterDomain }}
    path: /probe
    port: http
    scheme: http
    scrapeTimeout: 5s
  jobLabel: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-blackbox-exporter
      app.kubernetes.io/name: prometheus-blackbox-exporter